//! Review L9 (`lfs-yl6`): an all ones tail body means "the thread ends
//! here", exactly as an absent tail tag does, and must not be read as a
//! block pair address.
//!
//! # The rule, derived from the oracle
//!
//! The C reference writes BOTH spellings of thread end and reads them
//! identically. `lfs_dir_drop` (`lfs.c:1831`) commits
//! `LFS_MKTAG(LFS_TYPE_TAIL + tail->split, 0x3ff, 8)` with body
//! `tail->tail` and no `lfs_pair_isnull` guard, so removing the last
//! directory in the global thread hands its predecessor a literal
//! `{LFS_BLOCK_NULL, LFS_BLOCK_NULL}` tail body. `lfs_dir_compact`
//! (`lfs.c:2003`) does guard on `!lfs_pair_isnull` and therefore omits
//! the tag for the same logical state.
//!
//! The reader never distinguishes them because it never consults a null
//! tail: `lfs_pair_isnull` (`lfs.c:292`) gates every walk over
//! `dir->tail` before the pair is fetched (`lfs.c:4410`, `:4639`,
//! `:4733`, `:4798`, `:4951`, `:5146`). Note the definition is an OR over
//! the two halves, not an AND. Were the sentinel ever fetched,
//! `lfs_dir_fetchmatch`'s bounds check (`lfs.c:1103`) would reject the
//! all ones address as `LFS_ERR_CORRUPT` outright, which is precisely the
//! failure this crate exhibited before the fix: mount returned
//! `Error::Corrupt` on a conforming C written image.
//!
//! `tests/vectors/13_null_tail.bin` is that image, generated by the
//! oracle itself; `tests/conformance.rs` mounts it. This file pins the
//! rule at the unit level, over inputs a generated vector cannot reach:
//! the HardTail flavor, and both orderings of a null tail against a real
//! one in the same log.

use littlefs2_pure::alloc::{scan_used_blocks, scan_used_with_single_buf, Bitmap};
use littlefs2_pure::storage::Storage;
use littlefs2_pure::tag::{Tag, TagType};
use littlefs2_pure::{Fs, MetadataReader, Path, ROOT_BLOCK_PAIR};

mod common;
use common::{BlockBuilder, MemStorage};

extern crate alloc;
use alloc::vec;
use alloc::vec::Vec;

/// The all ones pair body the C reference writes for "no tail".
const NULL_BODY: [u8; 8] = [0xFF; 8];

fn superblock_bodies() -> (Vec<u8>, Vec<u8>) {
    let mut donor = MemStorage::new();
    let mut scratch = common::make_buffer();
    Fs::format(&mut donor, &mut scratch).unwrap();
    let mut block0 = vec![0u8; MemStorage::BLOCK_SIZE];
    donor.read(0, 0, &mut block0).unwrap();
    let reader = MetadataReader::new(&block0).unwrap();
    let mut name: Option<Vec<u8>> = None;
    let mut geom: Option<Vec<u8>> = None;
    for entry in reader.iter_tags() {
        match entry.tag.tag_type() {
            TagType::Superblock => name = Some(entry.body.to_vec()),
            TagType::InlineStruct if entry.tag.id() == 0 && geom.is_none() => {
                geom = Some(entry.body.to_vec());
            }
            _ => {}
        }
    }
    (name.expect("superblock NAME"), geom.expect("geometry struct"))
}

fn program_block(storage: &mut MemStorage, block: u32, bytes: &[u8]) {
    for (i, chunk) in bytes.chunks(MemStorage::PROG_SIZE).enumerate() {
        storage.program(block, (i * MemStorage::PROG_SIZE) as u32, chunk).unwrap();
    }
}

fn pair_body(a: u32, b: u32) -> [u8; 8] {
    let mut body = [0u8; 8];
    body[0..4].copy_from_slice(&a.to_le_bytes());
    body[4..8].copy_from_slice(&b.to_le_bytes());
    body
}

/// Build a superblock-valid root whose log ends with the given sequence
/// of tail tags, applied in order (so the last one is the latest).
fn image_with_tails(tails: &[(TagType, [u8; 8])]) -> MemStorage {
    let (sb_name, sb_geom) = superblock_bodies();
    let mut root = BlockBuilder::new(MemStorage::BLOCK_SIZE, 1).unwrap();
    root.tag(Tag::new(true, TagType::Superblock, 0, sb_name.len() as u16), &sb_name).unwrap();
    root.tag(Tag::new(true, TagType::InlineStruct, 0, sb_geom.len() as u16), &sb_geom).unwrap();
    for (kind, body) in tails {
        root.tag(Tag::new(true, *kind, 0x3FF, 8), body).unwrap();
    }
    root.commit(0).unwrap();
    let bytes = root.finish();

    let mut storage = MemStorage::new();
    program_block(&mut storage, 0, &bytes);
    storage
}

fn tail_of(storage: &mut MemStorage, block: u32) -> Option<littlefs2_pure::BlockPair> {
    let mut buf = vec![0u8; MemStorage::BLOCK_SIZE];
    storage.read(block, 0, &mut buf).unwrap();
    MetadataReader::new(&buf).unwrap().tail()
}

// ---- The decode: the sentinel reads as thread end ----

#[test]
fn null_soft_tail_decodes_as_no_tail() {
    let mut storage = image_with_tails(&[(TagType::SoftTail, NULL_BODY)]);
    assert_eq!(
        tail_of(&mut storage, 0),
        None,
        "an all ones SoftTail body is thread end, not the address 0xFFFFFFFF"
    );
}

#[test]
fn null_hard_tail_decodes_as_no_tail() {
    // The C writer never emits a null HardTail mid-directory, so no valid
    // image is lost by terminating; chasing an all ones address is the
    // only alternative and it is strictly worse.
    let mut storage = image_with_tails(&[(TagType::HardTail, NULL_BODY)]);
    assert_eq!(tail_of(&mut storage, 0), None, "a null HardTail terminates rather than corrupts");
    let mut buf = vec![0u8; MemStorage::BLOCK_SIZE];
    storage.read(0, 0, &mut buf).unwrap();
    assert!(
        !MetadataReader::new(&buf).unwrap().is_hard_tail(),
        "with no tail to chase, the hard/soft discriminator must not claim a continuation"
    );
}

#[test]
fn half_null_pair_is_null_like_the_c_reference() {
    // `lfs_pair_isnull` (lfs.c:292) is an OR over the two halves. Half a
    // pair address is never independently meaningful, so a body with one
    // all ones half is malformed, not half valid, and must not be fetched.
    let mut body = pair_body(2, 3);
    body[4..8].copy_from_slice(&u32::MAX.to_le_bytes());
    let mut storage = image_with_tails(&[(TagType::SoftTail, body)]);
    assert_eq!(tail_of(&mut storage, 0), None, "either half all ones makes the pair null");
}

// ---- Ordering: the collapse happens after latest-tag-wins ----

#[test]
fn null_tail_after_a_real_tail_ends_the_thread() {
    // The pair threaded {2,3} and later un-threaded. Latest wins, so the
    // thread ends; resurrecting {2,3} would re-link a dropped directory.
    let mut storage =
        image_with_tails(&[(TagType::SoftTail, pair_body(2, 3)), (TagType::SoftTail, NULL_BODY)]);
    assert_eq!(tail_of(&mut storage, 0), None, "the later null tail supersedes the earlier link");
}

#[test]
fn real_tail_after_a_null_tail_is_still_honored() {
    // The inverse, and the reason the sentinel is collapsed only AFTER
    // latest-tag-wins resolves: an implementation that skipped null tail
    // tags during the scan would report {2,3} here by accident and None in
    // the test above by accident. Both answers must come from the ordering.
    let mut storage =
        image_with_tails(&[(TagType::SoftTail, NULL_BODY), (TagType::SoftTail, pair_body(2, 3))]);
    let tail = tail_of(&mut storage, 0).expect("the later real tail wins");
    assert_eq!((tail.a.as_u32(), tail.b.as_u32()), (2, 3));
}

// ---- Consumers: every walker sees thread end ----

#[test]
fn mount_accepts_an_explicit_null_soft_tail() {
    // The regression itself. Before the fix the gstate accumulation walk
    // handed the sentinel to the bounds check and mount returned Corrupt.
    let storage = image_with_tails(&[(TagType::SoftTail, NULL_BODY)]);
    let mut a = common::make_buffer();
    let mut b = common::make_buffer();
    Fs::mount(storage, &mut a, &mut b).expect("a null tail is thread end, not corruption");
}

#[test]
fn mount_accepts_an_explicit_null_hard_tail() {
    let storage = image_with_tails(&[(TagType::HardTail, NULL_BODY)]);
    let mut a = common::make_buffer();
    let mut b = common::make_buffer();
    Fs::mount(storage, &mut a, &mut b).expect("a null HardTail terminates the chain");
}

#[test]
fn allocator_walkers_accept_an_explicit_null_tail() {
    // Both forest walkers reject an out of range tail as Corrupt; the
    // sentinel must not reach that check.
    let mut storage = image_with_tails(&[(TagType::SoftTail, NULL_BODY)]);
    let mut used = Bitmap::EMPTY;
    let mut a = common::make_buffer();
    let mut b = common::make_buffer();
    scan_used_blocks(&mut storage, ROOT_BLOCK_PAIR, &mut used, &mut a, &mut b)
        .expect("the two buffer walker must read the sentinel as thread end");

    let mut used = Bitmap::EMPTY;
    let mut buf = common::make_buffer();
    scan_used_with_single_buf(&mut storage, ROOT_BLOCK_PAIR, &mut used, &mut buf)
        .expect("the single buffer walker owes the same reading");
}

// ---- The write side ----

/// Build the same history the C oracle used for `13_null_tail.bin`, but
/// with this crate's writer: `mkdir /a`, `mkdir /b`, a file in `/b`, then
/// remove the directory that ends the global thread.
fn rust_written_null_tail_image() -> MemStorage {
    let mut storage = MemStorage::new();
    let mut scratch = common::make_buffer();
    Fs::format(&mut storage, &mut scratch).unwrap();
    let mut a = common::make_buffer();
    let mut b = common::make_buffer();
    let mut fs = Fs::mount(storage, &mut a, &mut b).unwrap();
    fs.mkdir(Path::new("/a").unwrap(), &mut a, &mut b).unwrap();
    fs.mkdir(Path::new("/b").unwrap(), &mut a, &mut b).unwrap();
    fs.write_to_path(Path::new("/b/keep").unwrap(), b"KEEP", &mut a, &mut b).unwrap();
    fs.rmdir(Path::new("/a").unwrap(), &mut a, &mut b).unwrap();
    fs.into_storage()
}

#[test]
fn our_rmdir_of_the_last_threaded_directory_remounts() {
    // The write side must not produce an image its own reader rejects.
    // `unthread_and_steal` passes the NONE sentinel as the predecessor's
    // new tail, which `apply_op_to_pair_inner` reads as "clear the tail"
    // and satisfies by compacting the tag away.
    let storage = rust_written_null_tail_image();
    let mut a = common::make_buffer();
    let mut b = common::make_buffer();
    let mut fs = Fs::mount(storage, &mut a, &mut b).expect("remount after un-threading");
    assert!(!fs.exists(Path::new("/a").unwrap(), &mut a, &mut b).unwrap());
    let mut names: Vec<Vec<u8>> = Vec::new();
    fs.list_dir(Path::new("/b").unwrap(), |e| names.push(e.name.to_vec()), &mut a, &mut b).unwrap();
    assert_eq!(names, vec![b"keep".to_vec()]);
}

#[test]
fn our_writer_spells_thread_end_as_an_absent_tag() {
    // Pin WHICH of the two legal spellings this crate emits, so a change
    // of encoding is a deliberate act rather than a silent drift. We write
    // the tag-absent form (`lfs_dir_compact`'s spelling, lfs.c:2003); the
    // oracle's `lfs_dir_drop` writes the sentinel instead. Both read as
    // thread end under both readers, which is what
    // `tests/conformance.rs::vector_13_*` and the `null_tail` roundtrip
    // scenario prove in their respective directions.
    let mut storage = rust_written_null_tail_image();
    let mut found_sentinel = false;
    let mut buf = vec![0u8; MemStorage::BLOCK_SIZE];
    for blk in 0..MemStorage::BLOCK_COUNT {
        storage.read(blk, 0, &mut buf).unwrap();
        let Ok(reader) = MetadataReader::new(&buf) else { continue };
        if !reader.has_commits() {
            continue;
        }
        for entry in reader.iter_tags() {
            if matches!(entry.tag.tag_type(), TagType::SoftTail | TagType::HardTail)
                && entry.body == NULL_BODY
            {
                found_sentinel = true;
            }
        }
    }
    assert!(
        !found_sentinel,
        "this crate is expected to spell thread end as an absent tail tag; \
         emitting the sentinel is legal too, but the change should be deliberate \
         and this assertion updated with it"
    );
}
